# Generated by Django 4.0.5 on 2024-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='paper_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='poster_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='presentation_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
