# Generated by Django 4.0.5 on 2022-06-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_researchpartner_song_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='pmd7211@gmail.com', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
