# Generated by Django 4.0.5 on 2022-06-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_researchpartner_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='carousel_photos/')),
                ('caption', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('time_created',),
            },
        ),
    ]
