# Generated by Django 4.0.5 on 2022-06-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_carouselphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('learn', 'Learn Quantum'), ('articles', 'Articles'), ('comps', 'Competitions + Games'), ('opps', 'Opportunities')], max_length=8)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-time_created',),
            },
        ),
        migrations.AlterModelOptions(
            name='carouselphoto',
            options={'ordering': ('-time_created',)},
        ),
    ]
