# Generated by Django 4.0.5 on 2022-06-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_resource_alter_carouselphoto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
