# Generated by Django 3.2.20 on 2024-06-11 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_display_first_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.FileField(upload_to='college_logos/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='display_first_last',
            field=models.BooleanField(default=False, verbose_name='Display first and last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.college'),
        ),
    ]
