# Generated by Django 4.0.5 on 2024-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20240611_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, help_text='Deprecated. Select college instead.', null=True, upload_to='student_photos/'),
        ),
    ]
