# Generated by Django 5.0.7 on 2025-02-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_college_options_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpartner',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='researchpartner',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
